name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - generated

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: generated
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1
